
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "jogo de damas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className= 'body'>
     
        {children}
     
      </body>
    </html>
  );
}
